### PR TITLE
All the breaking changes

### PR DESCRIPTION
**Pull request by krallin**
This includes a bunch of breaking changes that we have been pushing back on for a little while, but that we probably need to do at some point. Specifically:

- This upgrades latest to Ruby 2.4 (from 2.3) and Ubuntu 16.04 (from 12.04).
- This upgrades all Ubuntu images that have no OS specified (e.g. `2.3`, `ruby-2.3`, or `2.3-ubuntu`, but not `2.3-ubuntu-12.04`) to Ubuntu 16.04 (from 12.04). The old tags remain available if addressed explicitly. So, users of the tags `VERSION`, `ruby-VERSION` and `VERSION-ubuntu` can get back to what they had before with `VERSION-ubuntu-12.04`.
- This upgrades all Debian images that have no OS specified (e.g. `2.3-debian`, but not `2.3-debian-wheezy`) to Jessie (from Wheezy). Here again there is a way to get back to the old tags: `VERSION-debian`, `ruby-VERSION-debian` are available via `VERSION-debian-wheezy`.
- This bumps ruby 2.3 to 2.3.3 (from 2.3.1). This shouldn't be too much of an issue for users and it's coherent with [our upgrade policy](https://www.aptible.com/support/topics/enclave/aptible-docker-images/).

I've updated the README to only reference "recommend" tags that won't change over time.

---

cc @fancyremarker

### CODE REVIEW

**Comment by krallin** [comment]
I'm going to try and make a list of customers that have built using one of the old tags recently and reach out to them

**Comment by jwcarman** [comment]
I don't see any mention of the 2.2 stuff.  We're using:

FROM quay.io/aptible/ruby:2.2

Would we just need that to be:

FROM quay.io/aptible/ruby:2.2-ubuntu-12.04

if we don't wish to change our OS?

**Comment by fancyremarker** [comment]
@jwcarman : that's exactly correct.

**Comment by jwcarman** [comment]
Perfect!  Thank you for your quick response.

**Pull request merged**
